server:
  port: 8086
#通过调整日志的级别，打印map的url信息
logging:
  level:
    org:
      springframework:
        web:
          servlet:
            mvc:
              method:
                annotation:
                  RequestMappingHandlerMapping: trace

management:
  endpoints:
    web:
      exposure:
        # 这里用* 代表暴露所有端点只是为了观察效果，实际中按照需进行端点暴露
        include: "*"
  endpoint:
    health:
      # 详细信息显示给所有用户。
      show-details: always
  health:
    status:
      http-mapping:
        # 自定义健康检查返回状态码对应的 http 状态码
        FATAL:  503

#配置通过Zuul运行的服务的Hystrix超时2.5s，如果设置某个服务的，可以将下面的default换成对应的服务名称
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 2500
    account-service:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 7000

account-service:
  ribbon:
    ReadTimeout: 7000

zuul:
  #配置过滤头部的黑名单，默认情况下会过滤Cookie,Set-Cookie,Authorization，
  #显式配置出来之后不会过滤Authorization
  sensitive-headers: Cookie,Set-Cookie
