spring:
  application:
    name: zipkin-server

eureka:
  instance:
    #将服务的ip地址而非服务所在的主机名注册到eureka
    preferIpAddress: true
    #metadata-map是定义eruka的元数据，通过自定义的元数据lancher可以进行灰度部署
    metadata-map:
      lancher: 1
  client:
    #通过euraka注册服务
    registerWithEureka: true
    #在服务中构建其他服务实例的地址缓存，从而防止每次都要向eureka询问ip地址
    #每隔30秒服务会更新一次缓存
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:18088/eureka/