server:
  port: 8089
spring:
  application:
    name: config-server
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:///D:/CET/licensingservice,file:///D:/CET/accountservice
