server:
  port: 8089
spring:
  application:
    name: config-server
  # 以下内容使用git的方式提供配置
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HymanLiuTS/SpringCloudTS.git
          search-paths: licenseserviceconfig,accountserviceconfig,zuulserverconfig
          force-pull: true
#          username: xxxxxx
#          password: xxxxxx
# 以下注释部分是使用本地文件的方式提供配置
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
           # 访问接口时会把所有的配置文件的内容获取出来
 #         search-locations: file:///D:/CET/accountserviceconfig,file:///D:/CET/licenseserviceconfig
eureka:
  instance:
    #将服务的ip地址而非服务所在的主机名注册到eureka
    preferIpAddress: true
  client:
    #通过euraka注册服务
    registerWithEureka: true
    #在服务中构建其他服务实例的地址缓存，从而防止每次都要向eureka询问ip地址
    #每隔30秒服务会更新一次缓存
    fetch-registry: true
    service-url:
      defaultZone: http://127.0.0.1:8088/eureka/