server:
  port: 8089
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/HymanLiuTS/SpringCloudTS.git
          search-paths: licenseserviceconfig,accountserviceconfig
          force-pull: true
#          username: xxxxxx
#          password: xxxxxx
# 以下注释部分是使用本地文件的方式提供配置
#  profiles:
#    active: native
#  cloud:
#    config:
#      server:
#        native:
           # 访问接口时会把所有的配置文件的内容获取出来

#          search-locations: file:///D:/CET/licensingservice,file:///D:/CET/accountservice
